version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: node.Dockerfile
    restart: unless-stopped
    container_name: node-app
    ports:
      - "${SERVER_PORT:-5050}:${SERVER_PORT:-5050}"
    networks:
      - net1
    depends_on:
      - mongodb
    env_file:
    - .env

  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    restart: unless-stopped
    container_name: mongodb
    networks:
      - net1
    environment:
      - MONGO_INITDB_DATABASE=ljosc

networks:
  net1:
    driver: bridge
